version: '3'

services:
  subscheck-downloader:
    image: python:3.9-alpine
    container_name: subscheck-downloader
    volumes:
      - ./downloads:/app/downloads
      - ./download-script.py:/app/download-script.py
    working_dir: /app
    command: >
      sh -c "
        pip install requests &&
        python download-script.py
      "
    restart: "no"  # 运行一次后停止
    environment:
      - TZ=Asia/Shanghai  # 设置时区
