name: Download SubsCheck URLs

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

# 添加权限设置
permissions:
  contents: write  # 给予写入仓库内容的权限

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史记录，避免浅克隆问题

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Download files
        run: |
          python download-script.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add downloads/
          git commit -m "Update downloaded files" -a || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          # 可以使用自定义的个人访问令牌（需要在仓库设置中添加）
          # 如果没有设置PAT_TOKEN，则使用默认的GITHUB_TOKEN
          github_token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
